CURRENCY_SYMBOLS = {
    "USD": "$",
    "EUR": "€",
    "GBP": "£",
    "CAD": "$",
    "AUD": "$",
    "JPY": "¥",
    "INR": "₹",
    "NZD": "$",
    "SGD": "$",
    "CHF": "CHF",
    "THB": "฿",
    "ZAR": "R",
    "RUB": "₽",
    "HKD": "$",
    "CNY": "¥",
    "MXN": "$",
    "PHP": "₱",
    "TWD": "NT$",
}